version: '3.7'
services:
  postgres:
    build: postgres
    container_name: blog-postgres
    restart: always
    ports:
      - '6432:5432'
    volumes:
      - '/volumes/blog/postgres/data:/var/lib/postgresql/data:rw'
    networks:
      - blog-network
    env_file:
      - postgres/postgres.env
networks:
  blog-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.200.0.0/16
